export const games = [
{id:1,
name:'battelfield V',
img:'assets/posts/battelfield.jpg',
mini_desc:'game by electronic arts 2018',
description:'Battlefield V is a first-person shooter video game developed by EA DICE and published by Electronic Arts. Battlefield V is the sixteenth installment in the Battlefield series. It was released worldwide for Microsoft Windows, PlayStation 4, and Xbox One on November 20, 2018.',
trailer:'https://www.youtube.com/embed/a7ZpQadiyqs',
logo:'assets/posts/battelfield_logo.png'},
{id:2,
name:`assassin's creed III`,
img:'assets/posts/assassins_creed-1.png',
mini_desc:'game by ubisoft 2012',
description:`Assassin's Creed III is a 2012 action-adventure video game developed by Ubisoft Montreal and published by Ubisoft for PlayStation 3, Xbox 360, Wii U, and Microsoft Windows. It is the fifth major installment in the Assassin's Creed series, and a direct sequel to 2011's Assassin's Creed: Revelations.`,
trailer:'https://www.youtube.com/embed/-pUhraVG7Ow',
logo:'assets/posts/assassins_creed_logo.jpg'},
{id:3,
name:'forza horizon 4',
img:'assets/posts/forza.jpg',
mini_desc:'game by turn 10 studios 2018',
description:`Forza Horizon 4 is a 2018 racing video game developed by Playground Games and published by Xbox Game Studios. It was released on 2 October 2018 on Xbox One and Microsoft Windows after being announced at Xbox's E3 2018 conference. An enhanced version of the game is set to release on Xbox Series X/S on 10 November 2020.`,
trailer:'https://www.youtube.com/embed/5xy4n73WOMM',
logo:''},
{id:4,
name:'god of war 4',
img:'assets/posts/kratos.jpg',
mini_desc:'game by sie 2018',
description:`God of War is an action-adventure game developed by Santa Monica Studio and published by Sony Interactive Entertainment. Released on April 20, 2018, for the PlayStation 4, it is the eighth installment in the God of War series, the eighth chronologically, and the sequel to 2010's God of War III`,
trailer:'https://www.youtube.com/embed/K0u_kAWLJOA',
logo:''},
{id:5,
name:'L.A Noire',
img:'assets/posts/lanoire.jpg',
mini_desc:'game by rockstar 2011',
description:'L.A. Noire is a neo-noir detective action-adventure video game developed by Team Bondi and published by Rockstar Games. It was released in May 2011 for PlayStation 3 and Xbox 360, in November 2011 for Microsoft Windows, and in November 2017 for Nintendo Switch, PlayStation 4 and Xbox One',
trailer:'https://www.youtube.com/embed/ZbPxNGh7dto',
logo:''},
{id:6,
name:'Mafia II',
img:'assets/posts/mafia2.jpg',
mini_desc:'game by 2k games 2010',
description:`Mafia II is a 2010 action-adventure game developed by 2K Czech and published by 2K Games. It was released in August for Microsoft Windows, PlayStation 3, and Xbox 360; Mafia II: Director's Cut was released by Feral Interactive in December 2011.`,
trailer:'https://www.youtube.com/embed/S1J3jM8EbSE',
logo:''},
{id:7,
name:'mortal kombat XI',
img:'assets/posts/mk.jpg',
mini_desc:'game by warner bros 2019',
description:'Mortal Kombat 11 is a fighting game developed by NetherRealm Studios and published by Warner Bros. Interactive Entertainment.',
trailer:'https://www.youtube.com/embed/bxFoRCvEjUA',
logo:''},
{id:8,
name:'gta V',
img:'assets/posts/gta-v.jpg',
mini_desc:'game by rockstar 2013',
description:`Grand Theft Auto V is a 2013 action-adventure game developed by Rockstar North and published by Rockstar Games. It is the first main entry in the Grand Theft Auto series since 2008's Grand Theft Auto IV.`,
trailer:'https://www.youtube.com/embed/QkkoHAzjnUs',
logo:''},
{id:9,
name:'PUBG',
img:'assets/posts/pubg.jpg',
mini_desc:'game by pubg corporation 2017',
description:`Description. The official PLAYERUNKNOWN'S BATTLEGROUNDS designed exclusively for mobile. Play free anywhere, anytime. PUBG MOBILE delivers the most intense free-to-play multiplayer action on mobile. Drop in, gear up, and compete.`,
trailer:'https://www.youtube.com/embed/ODWCbu_cuqk',
logo:''},
{id:10,
name:'CS GO',
img:'assets/posts/csgo.png',
mini_desc:'game by valve corporation 2012',
description:`Counter-Strike: Global Offensive is a multiplayer first-person shooter video game developed by Valve and Hidden Path Entertainment. It is the fourth game in the Counter-Strike series and was released for Windows, OS X, Xbox 360, and PlayStation 3 in August 2012, while the Linux version was released in 2014.`,
trailer:'https://www.youtube.com/embed/edYCtaNueQY',
logo:''}
]
